Repository ouch-org/ouch, pull requests merged in 2021-11, with the labels that each got.

#129 Implement command 'list' to show archive contents
  Cargo.lock
  Cargo.toml
  src/archive/tar.rs
  src/archive/zip.rs
  src/cli.rs
  src/commands.rs
  src/lib.rs
  src/list.rs
  src/opts.rs
  src/utils.rs
Labels: hacktoberfest-accepted

#163 rewrite tests
  .gitignore
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  tests/compress_and_decompress.rs
  tests/compress_empty_dir.rs
  tests/integration.rs
  tests/mime.rs
  tests/utils.rs
Labels: bugfix

#154 Infer file extension when decompressing
  LICENSE
  src/commands.rs
  src/macros.rs
  src/utils/fs.rs
  src/utils/mod.rs
  src/utils/question_policy.rs
Labels: enhancement
